{% set version = "2.7.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: keras
  version: {{ version }}

source:
  - url: https://pypi.io/packages/py2.py3/k/keras/keras-{{ version }}-py2.py3-none-any.whl
    sha256: 0c33ae1f728064ca0d35dfba999e9c316f03623bf5688c82fb83cc74a80ea248
  - url: https://raw.githubusercontent.com/keras-team/keras/v{{ version }}/LICENSE
    sha256: ebc07b279109d4bd5e58fe06f54e8f8aee8ba1024b77b222bc04214ae6f56348

build:
  script: {{ PYTHON }} -m pip install -vv keras-{{ version }}-py2.py3-none-any.whl
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
  run_constrained:
    - tensorflow {{ major_minor }}.*

test:
  requires:
    - pip
  commands:
    - pip check
  # Cyclic dependency with tensorflow
  # imports:
  #  - keras

about:
  home: https://github.com/keras-team/keras
  license: Apache-2.0
  license_file: LICENSE
  summary: Deep Learning for Python

extra:
  recipe-maintainers:
    - mariusvniekerk
    - croth1
    - ocefpaf
    - xhochy
