{% set version = "2.0.6" %}
{% set sha256 = "0519480abe4ad18b2c2d1bc580eab75edd82c95083d341a1157952f4b00019bb" %}

package:
    name: keras
    version: {{ version }}

source:
    url: https://github.com/fchollet/keras/archive/{{ version }}.tar.gz
    fn: keras-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 1

requirements:
    build:
        - python
        - setuptools
    run:
        - h5py
        - numpy
        - setuptools
        - scipy
        - tensorflow <=1.0.1  # [osx]
        - python
        - pyyaml
        - six
        - theano  # [win or linux]

test:
    imports:
        - keras
        - keras.backend
        - keras.datasets
        - keras.engine
        - keras.layers
        - keras.preprocessing
        - keras.utils
        - keras.wrappers

about:
    home: https://github.com/fchollet/keras
    license: MIT
    summary: Deep Learning for Python

extra:
    recipe-maintainers:
        - ericdill
        - mariusvniekerk
        - croth1
