{% set version = "1.1.0" %}
{% set sha256 = "5dc69abb2b66e8e825d0c48037a334d0cd2f3d9e27bb1dcf20c8ba16c8b21c96" %}

package:
    name: keras
    version: {{ version }}

source:
    url: https://github.com/fchollet/keras/archive/{{ version }}.tar.gz
    fn: keras-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - h5py
        - numpy
        - setuptools
        - scipy
        - tensorflow  # [not win]
        - python
        - pyyaml
        - six
        - theano

test:
    imports:
        - keras
        - keras.backend
        - keras.datasets
        - keras.engine
        - keras.layers
        - keras.legacy
        - keras.preprocessing
        - keras.utils
        - keras.wrappers

about:
    home: https://github.com/fchollet/keras
    license: MIT
    summary: Deep Learning for Python

extra:
    recipe-maintainers:
        - ericdill
        - mariusvniekerk
