{% set version = "3.1.0" %}
# Version bump reminder: Must manually check the file constraints to ensure 
# they match those similar to
# 2024/01 hmaarrfk -- However we have found that these get somewhat stale
# https://keras.io/getting_started/#compatibility-matrix

package:
  name: keras
  version: {{ version }}

source:
  url: https://github.com/keras-team/keras/archive/refs/tags/v{{ version }}.tar.gz
  sha256: efcf3e3e7806dfd7016b8e1bf50e9247390231010b1bcf2217c2d79a1e70e5ae

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    # see https://github.com/keras-team/keras/blob/master/oss_setup.py
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - absl-py
    - numpy
    - rich
    - namex
    - h5py
    - dm-tree
    - ml_dtypes
  run_constrained:
    - tensorflow >=2.15.0,<2.17.0a
    - jax 0.4.*
    - pytorch 2.1.*

test:
  commands:
    - pip check
    # even the numpy backend requires jax....
    # https://github.com/keras-team/keras/issues/18840
    - KERAS_BACKEND=numpy python -c "import keras"
    - KERAS_BACKEND=jax python -c "import keras"
    - KERAS_BACKEND=tensorflow python -c "import keras"
    - KERAS_BACKEND=torch python -c "import keras"
  requires:
    # check if it exists a version that satisfy the run_constrained
    - jax
    - pytorch
    - tensorflow
    - pip

about:
  home: https://github.com/keras-team/keras
  license: Apache-2.0
  license_file: LICENSE
  summary: Deep Learning for Python

extra:
  recipe-maintainers:
    - ngam
    - mariusvniekerk
    - croth1
    - ocefpaf
    - xhochy
    - hmaarrfk
