{% set version = "2.6.0" %}

package:
  name: keras
  version: {{ version }}

source:
  - url: https://pypi.io/packages/py2.py3/k/keras/keras-{{ version }}-py2.py3-none-any.whl
    sha256: 504af5656a9829fe803ce48a8580ef16916e89906aceddad9e098614269437e7
  - url: https://raw.githubusercontent.com/keras-team/keras/v{{ version }}/LICENSE
    sha256: ebc07b279109d4bd5e58fe06f54e8f8aee8ba1024b77b222bc04214ae6f56348

build:
  script: {{ PYTHON }} -m pip install -vv keras-{{ version }}-py2.py3-none-any.whl
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
  run_constrained:
    - tensorflow {{ version }}.*

test:
  requires:
    - pip
  commands:
    - pip check
  # Cyclic dependency with tensorflow
  # imports:
  #  - keras

about:
  home: https://github.com/keras-team/keras
  license: Apache-2.0
  license_file: LICENSE
  summary: Deep Learning for Python

extra:
  recipe-maintainers:
    - mariusvniekerk
    - croth1
    - ocefpaf
    - xhochy
