{% set version = "2.2.1" %}
{% set sha256 = "46b8b495ec48fddbb36e59b99c4802b507ce60321141e1fd9a1418bc09f8c4f8" %}

package:
    name: keras
    version: {{ version }}

source:
    url: https://github.com/keras-team/keras/archive/{{ version }}.tar.gz
    fn: keras-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0

requirements:
    build:
        - python
        - pip
    run:
        - h5py
        - numpy >=1.9.1
        - scipy >=0.14
        - tensorflow     # [not (win and py27)]
        - python
        - pyyaml
        - six >=1.9.0
        - theano

test:
    imports:
        - keras
        - keras.backend
        - keras.datasets
        - keras.engine
        - keras.layers
        - keras.preprocessing
        - keras.utils
        - keras.wrappers

about:
    home: https://github.com/keras-team/keras
    license: MIT
    license_file: LICENSE
    summary: Deep Learning for Python

extra:
    recipe-maintainers:
        - ericdill
        - mariusvniekerk
        - croth1
