travis:
  secure:
    BINSTAR_TOKEN: ZqDp9swHfarjptP5qwtWLD+bvZM37D9vQqGHRMbTs0iOKi/wikp3X+1wxGpfUMY8wjACuclw7aTkZt059f6Zt5WVVSbWXh8FlbX4PhBsPCYzue/lGhiOTO/N/7iWYYBH2kfkGYj30Ln3aLT4c5W9tzBxmamgwdyaw6Cf54Pksrc3EMRGDzBwt8aLpatXFEweuh9HODJRvYoBRF3jbYBmS2VGDBR9i6ehE16kOvDYLufFkRW4XNXMLDX52yi1/O/Txi8wIVEhIpj7V3X11v3Cx3rdhEeniQrlXHL+HR//N7XOIiHgD7Xr+xC3F27B2RrhQFSievG1f+wLRj33gPXvWzQJquEsB7Dxn/gT/EDYm7T5SQLij27pUGDWCkME3TS0alQKnk3VQG3Lu2f5LBJf8+mFCzWZYkGiyz9fk9MFIIVsb69SRWbl4VQvMYzKh8xPBX1ZMTpSiZa1txPP6Btg0uwIh5ysU5TJ3JwwRNH8n/4am2BxzpcK1HjloXF9HW1vR2QatJDkVxCqnvyiKnfA9arooaRbYnhrhpS3pdwo1IsQJ3OvHXGTIK54vGRsaant1uC8SjEhOKTPmKOscvSdkoLYTa3ChtNtBncBaQFMAb+HzLrpinS2zCpDOvddttzCR0IYAbjH8TZ0SHDs+P98RFB4Q+8LD4R10ERcQwi9WMI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
